# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/changjian/VideoModel/Kinetics-FeatureExtractor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/changjian/VideoModel/Kinetics-FeatureExtractor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/changjian/VideoModel/Kinetics-FeatureExtractor/CMakeFiles /data/changjian/VideoModel/Kinetics-FeatureExtractor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/changjian/VideoModel/Kinetics-FeatureExtractor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppInterface

# Build rule for target.
CppInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CppInterface
.PHONY : CppInterface

# fast build rule for target.
CppInterface/fast:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/build
.PHONY : CppInterface/fast

ActiveLoader.o: ActiveLoader.cpp.o

.PHONY : ActiveLoader.o

# target to build an object file
ActiveLoader.cpp.o:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/ActiveLoader.cpp.o
.PHONY : ActiveLoader.cpp.o

ActiveLoader.i: ActiveLoader.cpp.i

.PHONY : ActiveLoader.i

# target to preprocess a source file
ActiveLoader.cpp.i:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/ActiveLoader.cpp.i
.PHONY : ActiveLoader.cpp.i

ActiveLoader.s: ActiveLoader.cpp.s

.PHONY : ActiveLoader.s

# target to generate assembly for a file
ActiveLoader.cpp.s:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/ActiveLoader.cpp.s
.PHONY : ActiveLoader.cpp.s

CppInterface.o: CppInterface.cpp.o

.PHONY : CppInterface.o

# target to build an object file
CppInterface.cpp.o:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/CppInterface.cpp.o
.PHONY : CppInterface.cpp.o

CppInterface.i: CppInterface.cpp.i

.PHONY : CppInterface.i

# target to preprocess a source file
CppInterface.cpp.i:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/CppInterface.cpp.i
.PHONY : CppInterface.cpp.i

CppInterface.s: CppInterface.cpp.s

.PHONY : CppInterface.s

# target to generate assembly for a file
CppInterface.cpp.s:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/CppInterface.cpp.s
.PHONY : CppInterface.cpp.s

LazyLoader.o: LazyLoader.cpp.o

.PHONY : LazyLoader.o

# target to build an object file
LazyLoader.cpp.o:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/LazyLoader.cpp.o
.PHONY : LazyLoader.cpp.o

LazyLoader.i: LazyLoader.cpp.i

.PHONY : LazyLoader.i

# target to preprocess a source file
LazyLoader.cpp.i:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/LazyLoader.cpp.i
.PHONY : LazyLoader.cpp.i

LazyLoader.s: LazyLoader.cpp.s

.PHONY : LazyLoader.s

# target to generate assembly for a file
LazyLoader.cpp.s:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/LazyLoader.cpp.s
.PHONY : LazyLoader.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/CppInterface.dir/build.make CMakeFiles/CppInterface.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CppInterface"
	@echo "... edit_cache"
	@echo "... ActiveLoader.o"
	@echo "... ActiveLoader.i"
	@echo "... ActiveLoader.s"
	@echo "... CppInterface.o"
	@echo "... CppInterface.i"
	@echo "... CppInterface.s"
	@echo "... LazyLoader.o"
	@echo "... LazyLoader.i"
	@echo "... LazyLoader.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

